#FROM tensorflow/tensorflow:2.3.0-gpu
FROM tensorflow/tensorflow:1.15.2-gpu

RUN apt-get update && apt-get install -y --no-install-recommends \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* 
    

# Recommended way to create a subdirectory is to not rely on WORKDIR to create
# it. WORKDIR doesn't have any chown capabilities, and we need the app 
# directory to be user owned, as pytest creates some cache files.
# https://github.com/moby/moby/issues/36677
RUN mkdir app && chown 1000 app
WORKDIR /app
# These next two folders will be where we will mount our local data and out
# directories. We create them manually (automatic creation when mounting will
# create them as being owned by root, and then our program cannot use them).
RUN mkdir data && chown 1000 data
RUN mkdir out && chown 1000 out

# RUN pip install opencv-python
COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

COPY --chown=1000 ./ ./

# Install our own project as a module.
# This is done so the tests can import it.
RUN pip install .
