FROM tensorflow/tensorflow:2.3.0-gpu

RUN apt-get update && apt-get install -y --no-install-recommends \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* 
    
RUN pip install opencv-python
WORKDIR /app
COPY --chown=1000 ./ ./
